version: "3"

services:
  postgres:
    build: ./postgres
    environment:
      - TZ=${TZ}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_TEST_DB=${POSTGRES_TEST_DB}
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - web

  python:
    build: ./python
    environment:
      - TZ=${TZ}
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
    ports:
      - 8080:8080
    networks:
      - web

volumes:
  postgres-data:

networks:
  web:
